---
sudo: required # not really required anymore, doing this out of habit
dist: bionic # I Montana, dislike Bionic, but it is the most stable

matrix:
  fast_finish: true
  include:
    - name: ELK w Minikube kubectl HELM snapped running Python 3.7 on Focal
      dist: focal
      addons:
        snaps:
          - name: minikube
            confinement: classic
            channel: latest/stable
          - name: kubectl
            confinement: classic
            channel: latest/stable
          - name: helm
            confinement: classic
            channel: latest/stable
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - minikube version
        - helm version
        - kubectl version --client
      after_success:
        - deactivate
    - name: ELK w Minikube kubectl HELM snapped running Python 3.7 on bionic
      dist: bionic
      addons:
        snaps:
          - name: minikube
            confinement: classic
            channel: latest/stable
          - name: kubectl
            confinement: classic
            channel: latest/stable
          - name: helm
            confinement: classic
            channel: latest/stable
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - minikube version
        - helm version
        - kubectl version --client
      after_success:
        - deactivate
